[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[env]
CONFIG_PATH = "./.cargo/config.toml"

[tasks.release]
command = "cargo"
args = ["build", "--release", "--config", "${CONFIG_PATH}"]

[tasks.build]
dependencies = ["strip-debuginfo"]

[tasks.build-with-debuginfo]
command = "cargo"
args = ["build", "--config", "${CONFIG_PATH}"]

[tasks.strip-debuginfo]
dependencies = ["build-with-debuginfo"]
script = '''
#!/bin/bash -ex

SYMBOLS=$(nm "${KERNEL_PATH}" | head -n 1)

if [ -n "$SYMBOLS" ]; then
    objcopy --only-keep-debug "${KERNEL_PATH}" "${KERNEL_PATH}.debug"
    strip --strip-all "${KERNEL_PATH}"
fi
'''

[tasks.check]
command = "cargo"
args = ["check", "--target=${KERNEL_TARGET}", "${@}"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--target=${KERNEL_TARGET}", "${@}"]
