[package]
name = "util"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true

[features]
alloc = []

[dependencies]
custom_debug = "0.6.2"
macros = { path = "../macros" }
